spring.application.name=AgriChain-NA
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/agrichain
spring.datasource.username=root
spring.datasource.password=Harika

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect