# ===============================
# Application (API)
# ===============================
spring.application.name=AgriChain-IAM_
server.port=8090


# ===============================
# Database (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/agrichain
spring.datasource.username=root
spring.datasource.password=3#A9?sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG


# ===============================
# Jackson
# ===============================
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=Asia/Kolkata
``